/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_grafica;

/**
 *
 * @author migue
 */
public class Pantalla1 extends javax.swing.JFrame {

     private AgregarActividad PantallaAgr;
     
    public Pantalla1() {
        initComponents();
            PantallaAgr = new AgregarActividad();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        mostrarAgregarActividad = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("02:04:25 ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1384, 693));
        setMinimumSize(new java.awt.Dimension(1384, 693));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(102, 0, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1384, 693));
        jPanel1.setMinimumSize(new java.awt.Dimension(1384, 693));
        jPanel1.setPreferredSize(new java.awt.Dimension(1384, 693));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 16, 170, 147));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 544, 67));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("02:04:25 | 22/04/24");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 390, -1));

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 370, 40));

        mostrarAgregarActividad.setBackground(new java.awt.Color(0, 0, 255));
        mostrarAgregarActividad.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        mostrarAgregarActividad.setForeground(new java.awt.Color(255, 255, 255));
        mostrarAgregarActividad.setText("AGREGAR ACTIVIDAD");
        mostrarAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAgregarActividadActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarAgregarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 380, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>                        

    private void mostrarAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {                                                        
      
       PantallaAgr.setVisible(true);
       PantallaAgr.setLocationRelativeTo(null);
            
        
    }                                                       




    // Variables declaration - do not modify                     
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarAgregarActividad;
    // End of variables declaration                   
}
